name: part_sorter
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  logger: ^1.4.0
  sqflite: ^2.0.0+4
  sqflite_common_ffi: ^2.0.0+4
  path: ^1.8.2
  flutter:
    sdk: flutter
  flutter_translate: ^3.0.0
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  path_provider: ^2.0.12

dev_dependencies:
  
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/i18n/en.json
    - assets/i18n/pl.json
